import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth";

export async function GET(){try{await requireAdmin(); return NextResponse.json({products:await prisma.product.findMany({include:{images:true,variants:true},orderBy:{updatedAt:"desc"}})});}catch{return NextResponse.json({error:"Unauthorized"},{status:401});}}

export async function POST(request:Request){try{await requireAdmin(); const b=await request.json(); if(!b.name||!b.sku||!b.slug||!b.description||!b.mood) return NextResponse.json({error:"Name, SKU, slug, description and mood are required."},{status:400});
 const product=await prisma.product.create({data:{sku:b.sku,slug:b.slug,name:b.name,shortName:b.shortName||null,shortDescription:b.shortDescription||null,description:b.description,mood:b.mood,category:b.category||"Candles",status:b.status||"DRAFT",priceUSD:Number(b.priceUSD||0),sizeLabel:b.sizeLabel||null,waxType:b.waxType||null,wickType:b.wickType||null,burnTimeHours:b.burnTimeHours?Number(b.burnTimeHours):null,scentFamily:b.scentFamily||null,scentIntensity:b.scentIntensity||null,topNotes:b.topNotes||null,middleNotes:b.middleNotes||null,baseNotes:b.baseNotes||null,ingredients:b.ingredients||null,allergens:b.allergens||null,careInstructions:b.careInstructions||null,vesselMaterial:b.vesselMaterial||null,vesselColor:b.vesselColor||null,dimensions:b.dimensions||null,netWeight:b.netWeight||null,stock:Number(b.stock||0),featured:Boolean(b.featured),seoTitle:b.seoTitle||null,seoDescription:b.seoDescription||null,images:{create:(b.images||[]).filter(Boolean).map((url:string,i:number)=>({url,alt:b.name,sortOrder:i,isPrimary:i===0}))}}});
 return NextResponse.json({product});}catch(e){return NextResponse.json({error:"Unable to create product."},{status:500});}}

export async function PUT(request:Request){try{await requireAdmin(); const b=await request.json(); const {id,images,...data}=b; const product=await prisma.product.update({where:{id},data:{...data,priceUSD:data.priceUSD!==undefined?Number(data.priceUSD):undefined,burnTimeHours:data.burnTimeHours?Number(data.burnTimeHours):null,stock:data.stock!==undefined?Number(data.stock):undefined,featured:data.featured===undefined?undefined:Boolean(data.featured)}}); if(Array.isArray(images)){await prisma.productImage.deleteMany({where:{productId:id}}); await prisma.productImage.createMany({data:images.filter(Boolean).map((url:string,i:number)=>({productId:id,url,alt:product.name,sortOrder:i,isPrimary:i===0}))});} return NextResponse.json({product});}catch{return NextResponse.json({error:"Unable to update product."},{status:500});}}

export async function DELETE(request:Request){try{await requireAdmin(); const {id}=await request.json(); await prisma.product.delete({where:{id}}); return NextResponse.json({ok:true});}catch{return NextResponse.json({error:"Unable to delete product."},{status:500});}}
